NEW_USER = 'Новый пользователь'
TEST_NAME_GROUP = 'Тестовое название группы'
TEST_DESCRIP_GROUP = 'Тестовое описание группы'
TEXT_POST = 'Тестовый пост'
TEXT_POST_FORM = 'Тестовый пост формы'
NEW_TEXT_POST = 'Новый текст поста'
TEST_POST = 'Текст статьи'
TEST_GROUP = 'Группа статей'
TEST_SLUG = 'Тестовый слаг'
TEST_DESCRIPT = 'Тестовое описание'
NAME_GROUP = 'Название группы'
DESCRIPT = 'Описание группы'
AUTH = 'Автор статьи'
TEST_USER = 'Тестовый пользователь'
TEST_NAME = 'Тестовое название'
TEST_SLAG = 'test-slug'
TEST_DISCRIP = 'Тестовое описание'
SLUG = 'slug'
NO_AUTH = 'Не авторизованый пользователь'

DETAIL = 'posts:post_detail'
POST_CREATE = 'posts:post_create'
INDEX = 'posts:index'
PROFILE = 'posts:profile'
GROUP_LIST = 'posts:group_list'
EDIT = 'posts:post_edit'
DETAIL = 'posts:post_detail'

INDEX_HTML = 'posts/index.html'
CREATE_HTML = 'posts/create_post.html'
GROUP_LIST_HTML = 'posts/group_list.html'
PROFILE_HTML = 'posts/profile.html'
DETAIL_HTML = 'posts/post_detail.html'

TEST_OF_POST: int = 13
